//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroEduClass.Aero {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", ConfigurationName="Aero.iactiveMeetingServicePortType")]
    public interface iactiveMeetingServicePortType {
        
        // CODEGEN: Parameter 'args0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:roomOperate", ReplyAction="urn:roomOperateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.roomOperateResponse roomOperate(AeroEduClass.Aero.roomOperateRequest request);
        
        // CODEGEN: Parameter 'args0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:setDevicePerm", ReplyAction="urn:setDevicePermResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.setDevicePermResponse setDevicePerm(AeroEduClass.Aero.setDevicePermRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAuthGuid", ReplyAction="urn:getAuthGuidResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.getAuthGuidResponse getAuthGuid(AeroEduClass.Aero.getAuthGuidRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:iactiveMeetingList", ReplyAction="urn:iactiveMeetingListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.iactiveMeetingListResponse iactiveMeetingList(AeroEduClass.Aero.iactiveMeetingListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAuthGuidWithTime", ReplyAction="urn:getAuthGuidWithTimeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.getAuthGuidWithTimeResponse getAuthGuidWithTime(AeroEduClass.Aero.getAuthGuidWithTimeRequest request);
        
        // CODEGEN: Parameter 'args0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:roomPermOperate", ReplyAction="urn:roomPermOperateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.roomPermOperateResponse roomPermOperate(AeroEduClass.Aero.roomPermOperateRequest request);
        
        // CODEGEN: Parameter 'args2' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:setMeetingRole", ReplyAction="urn:setMeetingRoleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AeroEduClass.Aero.setMeetingRoleResponse setMeetingRole(AeroEduClass.Aero.setMeetingRoleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="roomOperate", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class roomOperateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        public roomOperateRequest() {
        }
        
        public roomOperateRequest(string args0, string args1, string args2) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="roomOperateResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class roomOperateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        public int @return;
        
        public roomOperateResponse() {
        }
        
        public roomOperateResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDevicePerm", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class setDevicePermRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=2)]
        public int args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=5)]
        public int args5;
        
        public setDevicePermRequest() {
        }
        
        public setDevicePermRequest(string args0, string args1, int args2, string args3, string args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDevicePermResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class setDevicePermResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        public int @return;
        
        public setDevicePermResponse() {
        }
        
        public setDevicePermResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAuthGuid", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class getAuthGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        public getAuthGuidRequest() {
        }
        
        public getAuthGuidRequest(string args0, string args1) {
            this.args0 = args0;
            this.args1 = args1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAuthGuidResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class getAuthGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getAuthGuidResponse() {
        }
        
        public getAuthGuidResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iactiveMeetingList", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class iactiveMeetingListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        public iactiveMeetingListRequest() {
        }
        
        public iactiveMeetingListRequest(string args0, string args1, string args2) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iactiveMeetingListResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class iactiveMeetingListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public iactiveMeetingListResponse() {
        }
        
        public iactiveMeetingListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAuthGuidWithTime", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class getAuthGuidWithTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=2)]
        public int args2;
        
        public getAuthGuidWithTimeRequest() {
        }
        
        public getAuthGuidWithTimeRequest(string args0, string args1, int args2) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAuthGuidWithTimeResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class getAuthGuidWithTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getAuthGuidWithTimeResponse() {
        }
        
        public getAuthGuidWithTimeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="roomPermOperate", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class roomPermOperateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        public roomPermOperateRequest() {
        }
        
        public roomPermOperateRequest(string args0, string args1, string args2) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="roomPermOperateResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class roomPermOperateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        public int @return;
        
        public roomPermOperateResponse() {
        }
        
        public roomPermOperateResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMeetingRole", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class setMeetingRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=1)]
        public long args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=3)]
        public int args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args5;
        
        public setMeetingRoleRequest() {
        }
        
        public setMeetingRoleRequest(int args0, long args1, string args2, int args3, string args4, string args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMeetingRoleResponse", WrapperNamespace="http://service.meeting.acenter.iactive.com.cn", IsWrapped=true)]
    public partial class setMeetingRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.meeting.acenter.iactive.com.cn", Order=0)]
        public int @return;
        
        public setMeetingRoleResponse() {
        }
        
        public setMeetingRoleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iactiveMeetingServicePortTypeChannel : AeroEduClass.Aero.iactiveMeetingServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iactiveMeetingServicePortTypeClient : System.ServiceModel.ClientBase<AeroEduClass.Aero.iactiveMeetingServicePortType>, AeroEduClass.Aero.iactiveMeetingServicePortType {
        
        public iactiveMeetingServicePortTypeClient() {
        }
        
        public iactiveMeetingServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iactiveMeetingServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iactiveMeetingServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iactiveMeetingServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.roomOperateResponse AeroEduClass.Aero.iactiveMeetingServicePortType.roomOperate(AeroEduClass.Aero.roomOperateRequest request) {
            return base.Channel.roomOperate(request);
        }
        
        public int roomOperate(string args0, string args1, string args2) {
            AeroEduClass.Aero.roomOperateRequest inValue = new AeroEduClass.Aero.roomOperateRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            AeroEduClass.Aero.roomOperateResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).roomOperate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.setDevicePermResponse AeroEduClass.Aero.iactiveMeetingServicePortType.setDevicePerm(AeroEduClass.Aero.setDevicePermRequest request) {
            return base.Channel.setDevicePerm(request);
        }
        
        public int setDevicePerm(string args0, string args1, int args2, string args3, string args4, int args5) {
            AeroEduClass.Aero.setDevicePermRequest inValue = new AeroEduClass.Aero.setDevicePermRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            AeroEduClass.Aero.setDevicePermResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).setDevicePerm(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.getAuthGuidResponse AeroEduClass.Aero.iactiveMeetingServicePortType.getAuthGuid(AeroEduClass.Aero.getAuthGuidRequest request) {
            return base.Channel.getAuthGuid(request);
        }
        
        public string getAuthGuid(string args0, string args1) {
            AeroEduClass.Aero.getAuthGuidRequest inValue = new AeroEduClass.Aero.getAuthGuidRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            AeroEduClass.Aero.getAuthGuidResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).getAuthGuid(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.iactiveMeetingListResponse AeroEduClass.Aero.iactiveMeetingServicePortType.iactiveMeetingList(AeroEduClass.Aero.iactiveMeetingListRequest request) {
            return base.Channel.iactiveMeetingList(request);
        }
        
        public string iactiveMeetingList(string args0, string args1, string args2) {
            AeroEduClass.Aero.iactiveMeetingListRequest inValue = new AeroEduClass.Aero.iactiveMeetingListRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            AeroEduClass.Aero.iactiveMeetingListResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).iactiveMeetingList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.getAuthGuidWithTimeResponse AeroEduClass.Aero.iactiveMeetingServicePortType.getAuthGuidWithTime(AeroEduClass.Aero.getAuthGuidWithTimeRequest request) {
            return base.Channel.getAuthGuidWithTime(request);
        }
        
        public string getAuthGuidWithTime(string args0, string args1, int args2) {
            AeroEduClass.Aero.getAuthGuidWithTimeRequest inValue = new AeroEduClass.Aero.getAuthGuidWithTimeRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            AeroEduClass.Aero.getAuthGuidWithTimeResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).getAuthGuidWithTime(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.roomPermOperateResponse AeroEduClass.Aero.iactiveMeetingServicePortType.roomPermOperate(AeroEduClass.Aero.roomPermOperateRequest request) {
            return base.Channel.roomPermOperate(request);
        }
        
        public int roomPermOperate(string args0, string args1, string args2) {
            AeroEduClass.Aero.roomPermOperateRequest inValue = new AeroEduClass.Aero.roomPermOperateRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            AeroEduClass.Aero.roomPermOperateResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).roomPermOperate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AeroEduClass.Aero.setMeetingRoleResponse AeroEduClass.Aero.iactiveMeetingServicePortType.setMeetingRole(AeroEduClass.Aero.setMeetingRoleRequest request) {
            return base.Channel.setMeetingRole(request);
        }
        
        public int setMeetingRole(int args0, long args1, string args2, int args3, string args4, string args5) {
            AeroEduClass.Aero.setMeetingRoleRequest inValue = new AeroEduClass.Aero.setMeetingRoleRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            AeroEduClass.Aero.setMeetingRoleResponse retVal = ((AeroEduClass.Aero.iactiveMeetingServicePortType)(this)).setMeetingRole(inValue);
            return retVal.@return;
        }
    }
}
